### PR TITLE
Add  ArrSort2

### PR DESCRIPTION
**Pull request by CallMeKohei**
Summary
---
'ArrSort2' is the Function that return the array having sorted elements.

Usage
---
```vb
Option Explicit

Sub SampleArrSort2()
    Debug.Print Dump(ArrSort2(Array(4, 7, 6, 2)))
End Sub
```
result
```vb
Array(2%, 4%, 6%, 7%)
```

The reason for the additional
---
To be able to briefly describe

describe by `ArrSort`  ---> Three lines need
```vb
Private Function StrMax(ByVal arr As Variant) As Long
    arr = StringWidth2(arr)
    ArrSort arr, False
    StrMax = arr(0)
End Function
```

describe by `ArrSort2`  ---> Only one line
```vb
Private Function StrMax(ByVal arr As Variant) As Long
    StrMax = ArrSort2(StringWidth2(arr), False)(0)
End Function
```

### CODE REVIEW

**Comment by CallMeKohei** [comment]
Known Bugs
---

```vb
Sub Sample20150226_Err()
    Debug.Print Dump(ArrSort2(Array(1, 3&, 2@, 5#)))
End Sub
```
result
```vb
Error 13
```
First aid
---
```vb
Sub Sample20150226_OK()
    Debug.Print Dump(ArrSort2(ArrToLng(Array(1, 3&, 2@, 5#))))
End Sub

Public Function ArrToLng(ByVal arr As Variant) As Variant
    ArrToLng = ArrMap(Init(New Func, vbVariant, AddressOf ToLng, vbVariant), arr)
End Function

Public Function ToLng(ByVal n As Variant) As Variant
    If IsNull(n) Or IsEmpty(n) Then n = 0
    ToLng = CLng(n)
End Function
```
result
```vb
Array(1&, 2&, 3&, 5&)
```

**Comment by igeta** [comment]
Core module is core of the library. What do you want to do?

**Comment by CallMeKohei** [comment]
I thought with the proposed function is an abstract operation. I was determined to add to its order core module is suitable. I hope that my proposal is accepted.

**Comment by igeta** [comment]
I can understand if say you should change it. But you say want to add.

**Comment by CallMeKohei** [comment]
If I'm sorry if I was uncomfortable for you. How my expression was incorrect. In fact, I have a request for you. I was representing the request content by writing the code that demand. I am glad if you to adopt my request to your library.

**Pull request closed without merging**
