### PR TITLE
Add IsJagArrTest.cls

### PR DESCRIPTION
**Pull request by CallMeKohei**
Summary
---
`IsJagArr` is the Function that determines whether or not the jugged array

Usage
---
```vb
Option Explicit

Sub SampleIsJagArr()
    
    Debug.Print IsJagArr(Array(0))
    Debug.Print IsJagArr(Array(Array(0), Array(1)))
    
End Sub
```
result
```vb
False
True
```

### CODE REVIEW

**Comment by CallMeKohei** [comment]
I was wrong operation. This pull request is a mistake.

**Comment by CallMeKohei** [comment]
I have also considered in relation to negative dimension！

**Comment by igeta** [comment]
Okey. Might as well. Please add to your own project.

**Comment by CallMeKohei** [comment]
Thank you for your Valuable advice!  I'll add this code to my project.

**Pull request closed without merging**
