### PR TITLE
Add IsNumericArr

### PR DESCRIPTION
**Pull request by CallMeKohei**
Summary
---
`IsNumericArr` is the function that determines the elements of the array is whether it is all the numbers.

Usage
---
```vb
Option Explicit

Sub SampleIsNumericArr()
    
    Debug.Print IsNumericArr(Array(0))
    Debug.Print IsNumericArr(Array("a"))
    
End Sub
```
result
```vb
True
False
```

---

### CODE REVIEW

**Comment by CallMeKohei** [comment]
Test Code
---
```vb
Option Explicit

' Assert.RunTestOf New IsNumericArrTest

Public Sub IsNumericArr_Test()
    
    'Assert.IsErrFunc 13, Init(New Func, vbBoolean, AddressOf IsNumericArr, vbVariant), vbObject

    Assert.AreEqual True, IsNumericArr(Array(1))
    Assert.AreEqual True, IsNumericArr(Array("1"))
    Assert.AreEqual True, IsNumericArr(Array("１"))
    Assert.AreEqual True, IsNumericArr(Array())
    Assert.AreEqual True, IsNumericArr(Array(Null))
    Assert.AreEqual True, IsNumericArr(Array(Empty))
    Assert.AreEqual True, IsNumericArr(Array(vbNull))
    Assert.AreEqual True, IsNumericArr(Array(vbEmpty))
    
    Assert.AreEqual False, IsNumericArr(Array("a"))
    Assert.AreEqual False, IsNumericArr(Array(ArrToClct(Array(1))))
    Assert.AreEqual False, IsNumericArr(Array(1, "a"))
    
End Sub
```

**Comment by CallMeKohei** [comment]
Test Code `ArrExplode`
---
```vb
Option Explicit

' Assert.RunTestOf New ArrExplodeTest

Public Sub ArrExplode_Test()

    Dim jagArr As Variant, arrx As ArrayEx
    
    Set arrx = New ArrayEx
    ArrExplode arrx, Array(Array(0))
    Assert.AreEqualArr Array(0), arrx.ToArray
    
    Set arrx = New ArrayEx
    ArrExplode arrx, Array(Array(0), Array(0))
    Assert.AreEqualArr Array(0, 0), arrx.ToArray
    
    Set arrx = New ArrayEx
    ArrExplode arrx, Array(Array(), Array(0))
    Assert.AreEqualArr Array(0), arrx.ToArray
    
    Set arrx = New ArrayEx
    ArrExplode arrx, Array(Array(0, 1), Array(2, 3))
    Assert.AreEqualArr Array(0, 1, 2, 3), arrx.ToArray

    Set arrx = New ArrayEx
    ArrExplode arrx, Array(Array(0, 1), Array(2, 3), Array())
    Assert.AreEqualArr Array(0, 1, 2, 3), arrx.ToArray
    
    Set arrx = New ArrayEx
    ArrExplode arrx, Array(Array(0, Array(1, 2)), Array(3, Array(4, 5)))
    Assert.AreEqualArr Array(0, 1, 2, 3, 4, 5), arrx.ToArray

    Set arrx = New ArrayEx
    ArrExplode arrx, Array(Array(0, Array(1, 2)), Array(3, Array(4, 5, Array())))
    Assert.AreEqualArr Array(0, 1, 2, 3, 4, 5), arrx.ToArray
    

    Set arrx = New ArrayEx:
    ArrExplode arrx, Array(Array(vbObject))
    Assert.AreEqualArr Array(vbObject), arrx.ToArray
    
    Set arrx = New ArrayEx
    ArrExplode arrx, Array(Array(vbObject), Array(0))
    Assert.AreEqualArr Array(vbObject, 0), arrx.ToArray
    
    Set arrx = New ArrayEx
    ArrExplode arrx, Array(Array(), Array(vbObject))
    Assert.AreEqualArr Array(vbObject), arrx.ToArray
    
    Set arrx = New ArrayEx
    ArrExplode arrx, Array(Array(vbObject, 1), Array(2, 3))
    Assert.AreEqualArr Array(vbObject, 1, 2, 3), arrx.ToArray

    Set arrx = New ArrayEx
    ArrExplode arrx, Array(Array(vbObject, 1), Array(2, 3), Array())
    Assert.AreEqualArr Array(vbObject, 1, 2, 3), arrx.ToArray
    
    Set arrx = New ArrayEx
    ArrExplode arrx, Array(Array(vbObject, Array(1, 2)), Array(3, Array(4, 5)))
    Assert.AreEqualArr Array(vbObject, 1, 2, 3, 4, 5), arrx.ToArray

    Set arrx = New ArrayEx
    ArrExplode arrx, Array(Array(vbObject, Array(1, 2)), Array(3, Array(4, 5, Array())))
    Assert.AreEqualArr Array(vbObject, 1, 2, 3, 4, 5), arrx.ToArray
    
    
End Sub
```

result
---
```vb
----------------------------------------------------------------------------
ArrExplodeTest
----------------------------------------------------------------------------
+ ArrExplode_Test
============================================================================
1 succeeded, 0 failed, took 0.00 seconds.
```

**Comment by igeta** [comment]
Should rename to IsNumericArrInTheSenceThatKoheiThink.

**Comment by CallMeKohei** [comment]
I have second thoughts, this function may not be abstract.
I also agree with the idea that this function is not suitable to the core module.

**Comment by igeta** [comment]
Core does not mean only abstract.

**Pull request closed without merging**
