### PR TITLE
Add IsJagArr

### PR DESCRIPTION
**Pull request by CallMeKohei**
Summary
---
`IsJagArr` is the Function that determines whether or not the jug array

Usage
---
```vb
Option Explicit

Sub SampleIsJagArr()
    
    Debug.Print IsJagArr(Array(0))
    Debug.Print IsJagArr(Array(Array(0), Array(1)))
    
End Sub
```
result
```vb
False
True
```

### CODE REVIEW

**Comment by CallMeKohei** [comment]
Known Bugs
---

```vb
Sub SampleIsJagArr_ShowBugs()
    
    Dim jagArr As Variant
    jagArr = Array(ArrToClct(Array()), ArrToClct(Array(0)), ArrToClct(Array(0, 0)))
    
    Debug.Print IsJagArr(jagArr)
    
End Sub
```
result
```vb
False
```

**Comment by CallMeKohei** [comment]
Test Code
---

```vb
Option Explicit

' Assert.RunTestOf New IsJagArrTest

Public Sub IsJagArr_Test()
    
    'Case of Not Array
    'Assert.IsErrFunc 13, Init(New Func, vbBoolean, AddressOf IsJagArr, vbVariant), 0

    'Case of Jag Array
    
    Dim jagArr1 As Variant: jagArr1 = Array(Array(1, 2, 3), Array(4, 5, 6))
    Dim jagArr2 As Variant: jagArr2 = Array(Array(1, 2, 3), Array(4, 5, 6), Array(7, 8, 9))

    Dim jagArr3 As Variant: jagArr3 = Array(Array(1), Array(2, 3, 4), Array(5, 6))
    Dim jagArr4 As Variant: jagArr4 = Array(Array(), Array(1, 2, 3), Array(4, 5))
    Dim jagArr5 As Variant: jagArr5 = Array(ArrToClct(Array()), ArrToClct(Array(0)), ArrToClct(Array(0, 0)))


    Assert.AreEqual True, IsJagArr(jagArr1), "jagArr1"
    Assert.AreEqual True, IsJagArr(jagArr2), "jagArr2"
    Assert.AreEqual True, IsJagArr(jagArr3), "jagArr3"
    Assert.AreEqual True, IsJagArr(jagArr4), "jagArr4"
    Assert.AreEqual True, IsJagArr(jagArr5), "jagArr5"
    
    
    'Case of 2D Array converted from Jag Array

    Dim vArr1 As Variant: vArr1 = JagArrToArr2D(jagArr1)
    Dim vArr2 As Variant: vArr2 = JagArrToArr2D(jagArr2)

    Assert.AreEqual False, IsJagArr(vArr1), "vArr1"
    Assert.AreEqual False, IsJagArr(vArr2), "vArr2"
    
    
    'Case of 1D Array
    
    Dim arr1D() As Variant
    Dim arr1DNll(vbNull) As Variant
    Dim arr1DEmp(vbEmpty) As Variant
    Dim arr1DObj(vbObject) As Variant
    
    Dim arr1DInt(0) As Integer
    Dim arr1DLng(0) As Long
    Dim arr1DSng(0) As Single
    Dim arr1DDbl(0) As Double
    Dim arr1DCur(0) As Currency
    Dim arr1DByt(0) As Byte
    Dim arr1DDat(0) As Date
    Dim arr1DVar(0) As Variant
    
    Dim arr1DClct() As Variant: arr1DClct = Array(ArrToClct(Array(0)))
    
    Assert.AreEqual False, IsJagArr(arr1D), "arr1D"
    Assert.AreEqual False, IsJagArr(arr1DNll), "arr1DNll"
    Assert.AreEqual False, IsJagArr(arr1DEmp), "arr1DEmp"
    Assert.AreEqual False, IsJagArr(arr1DObj), "arr1DObj"

    Assert.AreEqual False, IsJagArr(arr1DInt), "arr1DInt"
    Assert.AreEqual False, IsJagArr(arr1DLng), "arr1DLng"
    Assert.AreEqual False, IsJagArr(arr1DSng), "arr1DSng"
    Assert.AreEqual False, IsJagArr(arr1DDbl), "arr1DDbl"
    Assert.AreEqual False, IsJagArr(arr1DCur), "arr1DCur"
    Assert.AreEqual False, IsJagArr(arr1DByt), "arr1DByt"
    Assert.AreEqual False, IsJagArr(arr1DDat), "arr1DDat"
    Assert.AreEqual False, IsJagArr(arr1DVar), "arr1DVar"
    
    Assert.AreEqual False, IsJagArr(arr1DClct), "arr1DClct"
    
    
    'Case of 2D Array
    
    Dim arr2DNll(vbNull, vbNull) As Variant
    Dim arr2DEmp(vbEmpty, vbEmpty) As Variant
    Dim arr2DObj(vbObject, vbObject) As Variant
    
    Dim arr2DInt(0, 0) As Integer
    Dim arr2DLng(0, 0) As Long
    Dim arr2DSng(0, 0) As Single
    Dim arr2DDbl(0, 0) As Double
    Dim arr2DCur(0, 0) As Currency
    Dim arr2DByt(0, 0) As Byte
    Dim arr2DDat(0, 0) As Date
    Dim arr2DVar(0, 0) As Variant
    
    Dim arr2DClct() As Variant: arr2DClct = Array(ArrToClct(Array(0)), ArrToClct(Array(0)))
    
    Assert.AreEqual False, IsJagArr(arr2DNll), "arr2DNll"
    Assert.AreEqual False, IsJagArr(arr2DEmp), "arr2DEmp"
    Assert.AreEqual False, IsJagArr(arr2DObj), "arr2DObj"

    Assert.AreEqual False, IsJagArr(arr2DInt), "arr2DInt"
    Assert.AreEqual False, IsJagArr(arr2DLng), "arr2DLng"
    Assert.AreEqual False, IsJagArr(arr2DSng), "arr2DSng"
    Assert.AreEqual False, IsJagArr(arr2DDbl), "arr2DDbl"
    Assert.AreEqual False, IsJagArr(arr2DCur), "arr2DCur"
    Assert.AreEqual False, IsJagArr(arr2DByt), "arr2DByt"
    Assert.AreEqual False, IsJagArr(arr2DDat), "arr2DDat"
    Assert.AreEqual False, IsJagArr(arr2DVar), "arr2DVar"
    
    Assert.AreEqual False, IsJagArr(arr2DClct), "arr2DClct"
    
    
    'Case of 3D Array
    
    Dim arr3DNll(vbNull, vbNull, vbNull) As Variant
    Dim arr3DEmp(vbEmpty, vbEmpty, vbEmpty) As Variant
    Dim arr3DObj(vbObject, vbObject, vbObject) As Variant
    
    Dim arr3DInt(0, 0, 0) As Integer
    Dim arr3DLng(0, 0, 0) As Long
    Dim arr3DSng(0, 0, 0) As Single
    Dim arr3DDbl(0, 0, 0) As Double
    Dim arr3DCur(0, 0, 0) As Currency
    Dim arr3DByt(0, 0, 0) As Byte
    Dim arr3DDat(0, 0, 0) As Date
    Dim arr3DVar(0, 0, 0) As Variant
    
    Dim arr3DClct() As Variant: arr3DClct = Array(ArrToClct(Array(0)), ArrToClct(Array(0)), ArrToClct(Array(0)))
    
    Assert.AreEqual False, IsJagArr(arr3DNll), "arr3DNll"
    Assert.AreEqual False, IsJagArr(arr3DEmp), "arr3DEmp"
    Assert.AreEqual False, IsJagArr(arr3DObj), "arr3DObj"

    Assert.AreEqual False, IsJagArr(arr3DInt), "arr3DInt"
    Assert.AreEqual False, IsJagArr(arr3DLng), "arr3DLng"
    Assert.AreEqual False, IsJagArr(arr3DSng), "arr3DSng"
    Assert.AreEqual False, IsJagArr(arr3DDbl), "arr3DDbl"
    Assert.AreEqual False, IsJagArr(arr3DCur), "arr3DCur"
    Assert.AreEqual False, IsJagArr(arr3DByt), "arr3DByt"
    Assert.AreEqual False, IsJagArr(arr3DDat), "arr3DDat"
    Assert.AreEqual False, IsJagArr(arr3DVar), "arr3DVar"
    
    Assert.AreEqual False, IsJagArr(arr3DClct), "arr3DClct"
    
End Sub

```

**Comment by igeta** [comment]
I think Array() should be a jagged array. BTW.

```vba
Dim arr(-3 To -1) As Variant
arr(-3) = Array(1)
arr(-2) = Array(2)
arr(-1) = Array(3)
Debug.Print IsJagArr(arr)
```

**Comment by CallMeKohei** [comment]
Please look at the Add IsJagArrTest.cls # 12.

**Pull request closed without merging**
